#!/usr/bin/env bash
# Basado en: ~/.osx — http://mths.be/osx
# Adaptado a nuestra organizacion

###############################################################################
# Fresh Mac Stuff #
###############################################################################

echo "Borrando los PDF de ~/Downloads"
rm -r ~/Downloads/About\ Downloads.lpdf 2>/dev/null

echo "Borrando todos los iconos del Dock"
defaults write com.apple.dock persistent-apps -array

echo "Creando directorios Inbox, Action y Archive en ~"
mkdir ~/Inbox 2>/dev/null
mkdir ~/Action 2>/dev/null
mkdir ~/Archive 2>/dev/null

echo "Mostrar 'BlueHats' en el Login Screen"
sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText “BlueHats” 2>/dev/null

echo "Instalamos el bluehats wallpaper"
/usr/bin/osascript<<END
tell application "Finder"
set desktop picture to POSIX file "$HOME/Pictures/bluehats.jpg"
end tell
END

###############################################################################
# General UI/UX #
###############################################################################

echo "Standydelay a 24 horas (default es 1 hora)"
sudo pmset -a standbydelay 86400 2>/dev/null

echo "Desactivando efectos de sonido en el boot"
sudo nvram SystemAudioVolume=" " 2>/dev/null

echo "Desactivar warning cuando se borrar la papelera"
defaults write com.apple.finder WarnOnEmptyTrash -bool false 2>/dev/null
 
echo "Desactivar warning cuando cambias la extension de un archivo"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false 2>/dev/null

echo "Desactivar que Quicktime y Preview abran siempre lo ultimo que viste"
 defaults write com.apple.Preview NSQuitAlwaysKeepsWindows -bool false
 defaults write com.apple.QuickTimePlayerX NSQuitAlwaysKeepsWindows -bool false 2>/dev/null
 
echo "Desactivar icono de TimeMachine y Volumen"
for domain in ~/Library/Preferences/ByHost/com.apple.systemuiserver.*; do
   defaults write "${domain}" dontAutoLoad -array \
      "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
      "/System/Library/CoreServices/Menu Extras/Volume.menu" 
done
defaults write com.apple.systemuiserver menuExtras -array \
  "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
  "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
  "/System/Library/CoreServices/Menu Extras/Clock.menu"


echo "Mostrar siempre scrollbars"
defaults write NSGlobalDomain AppleShowScrollBars -string "Always" 2>/dev/null
# Possible values: `WhenScrolling`, `Automatic` and `Always`

echo "Desactivando animacion de cerrar/abrir aplicaciones"
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false 2>/dev/null

echo "Expandir save panel por default"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true 2>/dev/null

echo "Expandir print panel por default"
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true 2>/dev/null

echo "Grabar a disco (no iCloud) por default"
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false 2>/dev/null

echo "Desabilitar “Are you sure you want to open this application?” dialog"
defaults write com.apple.LaunchServices LSQuarantine -bool false 2>/dev/null

echo "Desabilitar Terminacion Automatica de apps trabadas"
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true 2>/dev/null

echo "Desabilitar SmartQuotes (Molesta al programar)"
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false 2>/dev/null

echo "Desabilitar SmartDashes (Molesta al programar)"
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false 2>/dev/null

echo "Desabilitar AutoCorrect por default"
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false 2>/dev/null


###############################################################################
# SSD-specific tweaks #
###############################################################################

echo "Desabilitar local TimeMachine snapshots"
sudo tmutil disablelocal

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input #
###############################################################################
echo "Trackpad: Activa tap to click"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true 2>/dev/null
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1 2>/dev/null
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1 2>/dev/null

echo "Trackpad: Rapido como su $%#$% madre"
defaults write -g com.apple.trackpad.scaling -int 5 2>/dev/null


echo "Activar Ctrl (^) para zoom"
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true 2>/dev/null
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144 2>/dev/null
 
echo "Iluminar teclado en condiciones de baja luz"
defaults write com.apple.BezelServices kDim -bool true 2>/dev/null

echo "Desactivar iluminación despues de 5 minutos de idle time"
defaults write com.apple.BezelServices kDimTime -int 300 2>/dev/null
 

echo "Activar Keyboard en todos lados"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3 2>/dev/null 

# Note: if you’re in the US, replace `EUR` with `USD`, `Centimeters` with
# `Inches`, `en_GB` with `en_US`, and `true` with `false`.
echo "Locale settings to en_US, USD, centimers"
defaults write NSGlobalDomain AppleLanguages -array "en" "nl" 2>/dev/null
defaults write NSGlobalDomain AppleLocale -string "en_US@currency=USD" 2>/dev/null
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters" 2>/dev/null
defaults write NSGlobalDomain AppleMetricUnits -bool true 2>/dev/null

echo "Trackpad: map bottom right corner to right-click"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2 2>/dev/null
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true 2>/dev/null
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1 2>/dev/null
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true 2>/dev/null

###############################################################################
# Security Features #
###############################################################################
echo "Requerir password inmediatamente despues de sleepmode o screensaver"
defaults write com.apple.screensaver askForPassword -int 1 2>/dev/null
defaults write com.apple.screensaver askForPasswordDelay -int 0 2>/dev/null

echo "Screenlock con 1 minuto"
defaults -currentHost write com.apple.screensaver askForPassword -int 1 2>/dev/null
defaults -currentHost write com.apple.screensaver askForPasswordDelay -int 60 2>/dev/null


echo "Activando Firewall"
sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1 2>/dev/null


echo "Borrar Papelera de manera segura por default"
defaults write com.apple.finder EmptyTrashSecurely -bool true 2>/dev/null

###############################################################################
# Finder #
###############################################################################
echo "Activar CMD+Q para Finder"
defaults write com.apple.finder QuitMenuItem -bool true 2>/dev/null

echo "Finder: desabilitar window animations y Get Info animations"
defaults write com.apple.finder DisableAllAnimations -bool true 2>/dev/null

echo "Finder: ~ para todas las ventanas nuevas"
defaults write com.apple.finder NewWindowTarget -string "PfDe" 2>/dev/null
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/" 2>/dev/null

echo "Finder: Mostrar discos duros, usbs y servidores externos en el Desktop"
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true 2>/dev/null
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true 2>/dev/null
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true 2>/dev/null
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true 2>/dev/null


echo "Finder: mostrar todas las extensiones"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true 2>/dev/null


echo "Finder: show status bar"
defaults write com.apple.finder ShowStatusBar -bool true 2>/dev/null

echo "Finder: show path bar"
defaults write com.apple.finder ShowPathbar -bool true 2>/dev/null

echo "Finder: allow text selection in Quick Look"
defaults write com.apple.finder QLEnableTextSelection -bool true 2>/dev/null

echo "Finder: Cuando se este buscando, buscar en el folder actual por default"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf" 2>/dev/null

echo "Finder: Springloading para directorios"
defaults write NSGlobalDomain com.apple.springing.enabled -bool true 2>/dev/null

echo "Finder: Evitar crear .DS_Stores en network volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true 2>/dev/null


# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
echo "Finder: ListView por default"
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv" 2>/dev/null


# Show the ~/Library folder
echo "Finder: Unhidden ~/Library folder"
chflags nohidden ~/Library 2>/dev/null
# Expand the following File Info panes:
# “General”, “Open with”, and “Sharing & Permissions”
echo "Finder: Expandir los siguientes FileInfo panles: General, Abrir con.., Permisos"
defaults write com.apple.finder FXInfoPanesExpanded -dict \
General -bool true \
OpenWith -bool true \
Privileges -bool true

echo "Finder: Guardar screenshots al desktop automaticamente"
defaults write com.apple.screencapture location -string "${HOME}/Desktop" 2>/dev/null

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
echo "Finder: Guardar screenshots con formato png por default"
defaults write com.apple.screencapture type -string "png" 2>/dev/null

echo "Finder: Desabilitar sombras en screenshots"
defaults write com.apple.screencapture disable-shadow -bool true 2>/dev/null


###############################################################################
# Dock, Dashboard, and hot corners #
###############################################################################

echo "Dock:iconos de tamaño 54 por default"
defaults write com.apple.dock tilesize -int 54 2>/dev/null

echo "Dock: Minimiza las ventanas hacia su aplicacion"
defaults write com.apple.dock minimize-to-application -bool true 2>/dev/null

echo "Dock: Remueve auto-hiding Dock delay"
defaults write com.apple.dock autohide-delay -float 0 2>/dev/null

echo "Dock: Auto-Hiding activado"
defaults write com.apple.dock autohide -bool true 2>/dev/null

echo "Dock: Iconos de apps hidden aparece traslucent"
defaults write com.apple.dock showhidden -bool true 2>/dev/null

echo "Dock: Agregando dos whitespaces para organizar iconos"
defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}' 2>/dev/null
defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}' 2>/dev/null

# Don’t automatically rearrange Spaces based on most recent use
echo "Spaces: Desactivar auto acomodo de spaces (se cambia solito y molesta)"
defaults write com.apple.dock mru-spaces -bool false 2>/dev/null

echo "Spaces: Acelera animaciones"
defaults write com.apple.dock expose-animation-duration -float 0.1 2>/dev/null

echo "Spaces: No mostrar dashboard como un space"
defaults write com.apple.dock dashboard-in-overlay -bool true 2>/dev/null


###############################################################################
# Safari & WebKit #
###############################################################################

echo "Safari: home page es `about:blank` para cargar mas rapido"
defaults write com.apple.Safari HomePage -string "about:blank" 2>/dev/null

echo "Safari: Prevenir abrir ‘safe’ files automaticamente despues de que se bajaron"
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false 2>/dev/null
 
echo "Safari: Desactivar thumbnail cache para History y Top Sites"
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2 2>/dev/null
 
echo "Safari: Activar debug menu"
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true 2>/dev/null

echo "Safari: Activar develop menu"
defaults write com.apple.Safari IncludeDevelopMenu -bool true 2>/dev/null
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true 2>/dev/null
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true 2>/dev/null
 
echo "Safari: Agregar item al context menu para que aparezca Web Inspector en webviews"
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true 2>/dev/null

echo "Safari: Desactivar que Backspace key te lleve a la pagina anterior"
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool false 2>/dev/null


###############################################################################
# Mail #
###############################################################################

echo "Mail: Desactivar animaciones de Reply y Send"
defaults write com.apple.mail DisableReplyAnimations -bool true
defaults write com.apple.mail DisableSendAnimations -bool true

# Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
echo "Mail: Copiar emails como 'email@ejemplo.com' en vez de 'Nombre <email@ejemplo.com'"
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false


###############################################################################
# Spotlight #
###############################################################################
# Change indexing order and disable some file types
echo "Spotlight: Cambiar orden de indexing y desactivar algunos tipos"
defaults write com.apple.spotlight orderedItems -array \
  '{"enabled" = 1;"name" = "APPLICATIONS";}' \
  '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
  '{"enabled" = 1;"name" = "DIRECTORIES";}' \
  '{"enabled" = 1;"name" = "PDF";}' \
  '{"enabled" = 1;"name" = "DOCUMENTS";}' \
  '{"enabled" = 1;"name" = "MESSAGES";}' \
  '{"enabled" = 1;"name" = "CONTACT";}' \
  '{"enabled" = 1;"name" = "SOURCE";}' \
  '{"enabled" = 0;"name" = "EVENT_TODO";}' \
  '{"enabled" = 1;"name" = "IMAGES";}' \
  '{"enabled" = 0;"name" = "BOOKMARKS";}' \
  '{"enabled" = 0;"name" = "MUSIC";}' \
  '{"enabled" = 1;"name" = "MOVIES";}' \
  '{"enabled" = 1;"name" = "PRESENTATIONS";}' \
  '{"enabled" = 1;"name" = "SPREADSHEETS";}'\
  '{"enabled" = 0;"name" = "FONTS";}' 

# Load new settings before rebuilding the index
killall mds > /dev/null 2>&1

# Make sure indexing is enabled for the main volume
sudo mdutil -i on / > /dev/null

echo "Spotlight: Re-hacer index desde cero"
sudo mdutil -E / > /dev/null

###############################################################################
# Terminal & iTerm 2 #
###############################################################################

echo "Terminal: Utilizar 'Pro' como Default Theme"
defaults write com.apple.terminal "Default Window Settings" -string "Pro"
defaults write com.apple.terminal "Startup Window Settings" -string "Pro"

echo "Terminal: Permitir unicamente UTF-8"
defaults write com.apple.terminal StringEncodings -array 4


###############################################################################
# Time Machine #
###############################################################################
# Prevent Time Machine from prompting to use new hard drives as backup volume
echo "Time Machine: Prevenir prompt cada vez que conectas un nuevo harddrive"
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable local Time Machine backups
echo "Time Machine: Desactivar local backups"
hash tmutil &> /dev/null && sudo tmutil disablelocal


###############################################################################
# Activity Monitor #
###############################################################################

# Show the main window when launching Activity Monitor
echo "Activity Monitor: Mostrar la venta principal al lanzar la app"
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Visualize CPU usage in the Activity Monitor Dock icon
echo "Activity Monitor: Visuarl CPU Usage en el Dock Icon"
defaults write com.apple.ActivityMonitor IconType -int 5

# Show all processes in Activity Monitor
echo "Activity Monitor: Mostrar todos los procesos por default"
defaults write com.apple.ActivityMonitor ShowCategory -int 0

# Sort Activity Monitor results by CPU usage
echo "Activity Monitor: Ordenar automatica por CPU Usage"
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0



###############################################################################
# Address Book, Dashboard, iCal, TextEdit, and Disk Utility #
###############################################################################

# Use plain text mode for new TextEdit documents
echo "TextEdit: Utilizar plain text mode por default"
defaults write com.apple.TextEdit RichText -int 0
# Open and save files as UTF-8 in TextEdit
echo "TextEdit: Abrir y Guardar archivos como UTF-8"
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4


###############################################################################
# Mac App Store #
###############################################################################
# Enable Debug Menu in the Mac App Store
echo "AppStore: Activar debug menu"
defaults write com.apple.appstore ShowDebugMenu -bool true


###############################################################################
# Transmission.app #
###############################################################################

# Use `~/Documents/Torrents` to store incomplete downloads
echo "Tranmission: Guardar archivos incompletos en ~/Documents/Torrents"
defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Documents/Torrents"

# Don’t prompt for confirmation before downloading
echo "Tranmission: Quitar prompt de confirmacion antes de descargar"
defaults write org.m0k.transmission DownloadAsk -bool false

# Trash original torrent files
echo "Tranmission: Eliminar archivos .torrent originales"
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

# Hide the donate message
echo "Tranmission: Ocultar mensaje de donacion"
defaults write org.m0k.transmission WarningDonate -bool false

echo "Tranmission: Ocultar mensaje legal"
defaults write org.m0k.transmission WarningLegal -bool false


###############################################################################
# Kill affected applications #
###############################################################################

for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
  "Dock" "Finder" "Mail" "Messages" "Safari" "SizeUp" "SystemUIServer" \
  "Terminal" "Transmission" "Twitter" "iCal"; do
  killall "${app}" > /dev/null 2>&1
done

